title: 2026 Groningen Semantic Metabolomics ELIXIR Workshop
description: Welcome to the official repository for the 2026 Groningen Semantic Metabolomics Workshop (ELIXIR RCI-M). All workshop materials, resources, and session notes will be shared here.

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
