name: msquality
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-msquality
  - bioconductor-mzr
  - devtools
  - r-devtools
  - r-jsonlite
  - r-languageserver
  - r-rlang
  - radian
